### ISSUE TITLE
能否在log中更改为可配置默认的logger

### ISSUE THREAD

**Issue by ThreeCatsLoveFish** [BotPlayerNeo/bili-live-api#1]
如题，我想用这个包作为我下游依赖，同时有非常多的直播间进行websocket链接，但是用底层包的之后每次新连接ws都会print进房成功，我看应该是log包中的default使用的是终端，能否加一个config可以选择装载自定义的logger，感谢！

**Comment by PlayerNeo42** [comment]
感谢建议，将在v0.2加入

**Comment by PlayerNeo42** [comment]
https://github.com/BotPlayerNeo/bili-live-api/releases/tag/v0.2.0

**Comment by ThreeCatsLoveFish** [comment]
感谢，已经用上了 👍
